### ISSUE TITLE
Numbers out of order after assertion failure.

### ISSUE THREAD

**Issue by cmonr** [ARMmbed/mbed-os-example-filesystem#22] opened 2017-12-19 23:45 UTC
Not sure how to reproduce this, but I figured the assertion error followed by the output would be helpful.

**Target:** Nucleo F746ZG
**Toolchain:** GCC_ARM
**Additional HW:** Mbed Flash Memory Shield

**Diff:**
```
diff --git a/main.cpp b/main.cpp
index bb30a33..c4674bd 100644
--- a/main.cpp
+++ b/main.cpp
@@ -27,17 +27,12 @@
 #include "LittleFileSystem.h"
 #include "FATFileSystem.h"
 
-
 // Physical block device, can be any device that supports the BlockDevice API
-SPIFBlockDevice bd(
-        MBED_CONF_SPIF_DRIVER_SPI_MOSI,
-        MBED_CONF_SPIF_DRIVER_SPI_MISO,
-        MBED_CONF_SPIF_DRIVER_SPI_CLK,
-        MBED_CONF_SPIF_DRIVER_SPI_CS);
+DataFlashBlockDevice bd(D11, D12, D13, D8);
 
 // File system declaration
 LittleFileSystem fs("fs");
-
+//FATFileSystem fs("fs");
 
 // Set up the button to trigger an erase
 InterruptIn irq(BUTTON1);
```

**Output:** (The glitch is where the MCU was reset by DAPLink)
```
--- Mbed OS fil▒--- Mbed OS filesystem example ---
Mounting the filesystem... lfs error: Corrupted dir pair at 0 1
lfs error: Invalid superblock at 536874384 536874084
Fail :(
No filesystem found, formatting... assertion "lfs->cfg->lookahead > 0" failed: f                                 ile ".\mbed-os\features\filesystem\littlefs\littlefs\lfs.c", line 1916, function                                 : lfs_init
--- Mbed OS filesystem example ---
Mounting the filesystem... OK
Opening "/fs/numbers.txt"... OK
Incrementing numbers (10/10)... OK
Closing "/fs/numbers.txt"... OK
Opening the root directory... OK
root directory:
    .
    ..
    numbers.txt
Closing the root directory... OK
Opening "/fs/numbers.txt"... OK
numbers:
    2
    3
    2
    4
    6
    2
    2
    3
    4
    5
Closing "/fs/numbers.txt"... OK
Unmounting... OK
Mbed OS filesystem example done!
Initializing the block device... OK
Erasing the block device... OK
Deinitializing the block device... OK
Initializing the block device... OK
Erasing the block device... OK
Deinitializing the block device... OK
Initializing the block device... OK
Erasing the block device... OK
Deinitializing the block device... OK
Initializing the block device... OK
Erasing the block device... OK
Deinitializing the block device... OK
Initializing the block device... OK
Erasing the block device... OK
Deinitializing the block device... OK
Initializing the block device... OK
Erasing the block device... OK
Deinitializing the block device... OK
--- Mbed OS filesystem example ---
Mounting the filesystem... OK
Opening "/fs/numbers.txt"... OK
Incrementing numbers (10/10)... OK
Closing "/fs/numbers.txt"... OK
Opening the root directory... OK
root directory:
    .
    ..
    numbers.txt
Closing the root directory... OK
Opening "/fs/numbers.txt"... OK
numbers:
    3
    4
    3
    5
    7
    3
    3
    4
    5
    6
Closing "/fs/numbers.txt"... OK
Unmounting... OK
Mbed OS filesystem example done!
--- Mbed OS filesystem example ---
Mounting the filesystem... OK
Opening "/fs/numbers.txt"... OK
Incrementing numbers (10/10)... OK
Closing "/fs/numbers.txt"... OK
Opening the root directory... OK
root directory:
    .
    ..
    numbers.txt
Closing the root directory... OK
Opening "/fs/numbers.txt"... OK
numbers:
    4
    5
    4
    6
    8
    4
    4
    5
    6
    7
Closing "/fs/numbers.txt"... OK
Unmounting... OK
Mbed OS filesystem example done!
--- Mbed OS filesystem example ---
Mounting the filesystem... OK
Opening "/fs/numbers.txt"... OK
Incrementing numbers (10/10)... OK
Closing "/fs/numbers.txt"... OK
Opening the root directory... OK
root directory:
    .
    ..
    numbers.txt
Closing the root directory... OK
Opening "/fs/numbers.txt"... OK
numbers:
    5
    6
    5
    7
    9
    5
    5
    6
    7
    8
Closing "/fs/numbers.txt"... OK
Unmounting... OK
Mbed OS filesystem example done!
--- Mbed OS filesystem example ---
Mounting the filesystem... OK
Opening "/fs/numbers.txt"... OK
Incrementing numbers (10/10)... OK
Closing "/fs/numbers.txt"... OK
Opening the root directory... OK
root directory:
    .
    ..
    numbers.txt
Closing the root directory... OK
```

**Comment by geky** [comment] 2018-03-09 20:57
Could not reproduce, chances are this has been fixed in master. Feel free to reopen if you can reproduce.

**Closed by geky** 2018-03-09 20:57 UTC
